fix(boxplot): hack boxplot into correct rendering using semiotic rc
spinnaker/deck-kayenta pull request #576
Opened 2021-04-14 21:26 UTC by anotherchrisberry

Semiotic V2 is always returning `0` for `x` on data points and hover annotations, which causes very bad graph rendering.

These changes are very tactical, very brittle, I am not proud of them, and I hope they go away once Semiotic cuts a new release.

__Behavior with Semiotic V1.x__
<img width="965" alt="Screen Shot 2021-04-14 at 2 15 44 PM" src="https://user-images.githubusercontent.com/73450/114781113-1963eb80-9d2d-11eb-88c9-1edab59c720b.png">

__With this PR__
<img width="967" alt="Screen Shot 2021-04-14 at 2 15 54 PM" src="https://user-images.githubusercontent.com/73450/114781118-1a951880-9d2d-11eb-8ce5-44f2e185e2b5.png">

__Without this PR__
<img width="1043" alt="Screen Shot 2021-04-14 at 2 25 52 PM" src="https://user-images.githubusercontent.com/73450/114781280-54661f00-9d2d-11eb-9273-1c745564cae2.png">

2021-04-14 21:27 UTC, anotherchrisberry commented on package.json
> +    "semiotic": "2.0.0-rc.12",
this makes no difference, I'm leaving it in the PR to show I tried

2021-04-14 21:27 UTC, anotherchrisberry commented on src/kayenta/report/detail/graph/semiotic/boxplot.tsx
> +        return <Annotation key={`${d.group}: ${name}`} noteData={noteData} />;
unrelated, but this cuts out a few duplicate key warnings

2021-04-15 02:39 UTC, ranihorev commented
Side notes: 
- I recommend updating the build command to `"build": "npm run clean && NODE_ENV=production rollup -c"`
- We need to upgrade the `@spinnaker/pluginsdk` to 0.0.26

2021-04-15 04:19 UTC, anotherchrisberry commented
> Side notes:
> 
> * I recommend updating the build command to `"build": "npm run clean && NODE_ENV=production rollup -c"`
> * We need to upgrade the `@spinnaker/pluginsdk` to 0.0.26

done done

2021-04-15 04:41 UTC, ranihorev requested changes
Looks like it works only for a very specific screen size :)
I can try fixing it tomorrow if you want

![image](https://user-images.githubusercontent.com/17147717/114814924-0c192200-9d6a-11eb-91b0-9b1dcd8444a5.png)

2021-04-15 06:10 UTC, anotherchrisberry commented
@ranihorev yeah, go for it! I played around with it some more but didn't have any luck.

I don't remember what the issue was that led to trying the RC version of semiotic, but there has been a more recent release of 1.x — maybe worth trying that if you don't have any luck, either.

2021-04-15 16:10 UTC, ranihorev commented
I tried reverting back but I'm getting this error:
`Cannot read property 'contourRenderFn' of undefined`

2021-04-15 21:21 UTC, closed without merging